name             'ssh_host_key'
maintainer       'Oliver Lundquist'
maintainer_email 'mail@oliverlundquist.com'
license          'All rights reserved'
description      'Generates necessary ssh host keys'
long_description 'Resolves "Could not load host key" error'
version          '1.0.0'
supports         'ubuntu', '= 14.04'
