name             'logrotate'
maintainer       'Oliver Lundquist'
maintainer_email 'mail@oliverlundquist.com'
license          'All rights reserved'
description      'Logrotate recipes'
long_description 'Configure various logrotate configs'
version          '1.0.0'
supports         'ubuntu', '= 14.04'
