name             'timezone'
maintainer       'Oliver Lundquist'
maintainer_email 'mail@oliverlundquist.com'
license          'All rights reserved'
description      'Sets the default system timezone'
long_description 'Sets the default system timezone'
version          '1.0.0'
supports         'ubuntu', '= 14.04'
